version: 2

defaults: &defaults
  working_directory: ~/project/vue-alert
  docker:
    - image: circleci/node:latest

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - vue-alert

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run build

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm test
      - run: npm run codecov

workflows:
  version: 2
  install-and-parallel-build-test:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - install